// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-kgFaCuV_-bocHxtRQ_HwOiashSk2qE0',
    appId: '1:79453872525:web:48351645a932695f151dc4',
    messagingSenderId: '79453872525',
    projectId: 'jewelry-ai-app-bba3d',
    authDomain: 'jewelry-ai-app-bba3d.firebaseapp.com',
    storageBucket: 'jewelry-ai-app-bba3d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNOWdIcX9v4zbss77xGaKx3bpVtjJbTOk',
    appId: '1:79453872525:android:e279be1adb5c3a16151dc4',
    messagingSenderId: '79453872525',
    projectId: 'jewelry-ai-app-bba3d',
    storageBucket: 'jewelry-ai-app-bba3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUEinteUUsrc4L6Q0NA9UlDO9cEIFPpmQ',
    appId: '1:79453872525:ios:3fa920486cfef0e3151dc4',
    messagingSenderId: '79453872525',
    projectId: 'jewelry-ai-app-bba3d',
    storageBucket: 'jewelry-ai-app-bba3d.firebasestorage.app',
    iosBundleId: 'com.example.jewelryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUEinteUUsrc4L6Q0NA9UlDO9cEIFPpmQ',
    appId: '1:79453872525:ios:3fa920486cfef0e3151dc4',
    messagingSenderId: '79453872525',
    projectId: 'jewelry-ai-app-bba3d',
    storageBucket: 'jewelry-ai-app-bba3d.firebasestorage.app',
    iosBundleId: 'com.example.jewelryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-kgFaCuV_-bocHxtRQ_HwOiashSk2qE0',
    appId: '1:79453872525:web:925dccc36b74ab56151dc4',
    messagingSenderId: '79453872525',
    projectId: 'jewelry-ai-app-bba3d',
    authDomain: 'jewelry-ai-app-bba3d.firebaseapp.com',
    storageBucket: 'jewelry-ai-app-bba3d.firebasestorage.app',
  );
}
